/**
 * notificationScheduler.js
 *
 * Automated push notifications (all times in IST = UTC+5:30):
 *
 *  • Good Morning     — 8:00 AM every day, AI-generated
 *  • Festival Check   — 8:05 AM every day, Groq checks if today is an Indian festival
 *  • Learning Nudge   — weekly, 4 randomly chosen days (max 1-day gap between them),
 *                       times selected from {10,13,16,20} with at most one repeat
 *  • Good Night       — 11:00 PM every day, AI-generated
 *
 * All message content is generated by Groq (llama-3.1-8b-instant).
 * Schedule stored in app_config so it survives restarts.
 */

import OpenAI from "openai";
import { sendPushBroadcast } from "./push.js";
import { query } from "./db.js";

// ── Task AI client (OpenAI-compatible, configured via env vars) ───────────────
const taskAI = new OpenAI({
  baseURL: process.env.TASK_AI_BASE_URL || "https://api.groq.com/openai/v1",
  apiKey:  process.env.TASK_AI_API_KEY  || process.env.GROQ_API_KEY || "missing-task-ai-key",
});
const TASK_AI_MODEL = process.env.TASK_AI_MODEL || "llama-3.1-8b-instant";

// ── IST helpers (IST = UTC + 330 min) ────────────────────────────────────────
function nowIST() {
  return new Date(Date.now() + 330 * 60 * 1000);
}

function istDateStr(d) {
  return d.toISOString().slice(0, 10);
}

function isoWeekKey(d) {
  const tmp = new Date(d);
  tmp.setUTCHours(0, 0, 0, 0);
  tmp.setUTCDate(tmp.getUTCDate() + 4 - (tmp.getUTCDay() || 7));
  const yearStart = new Date(Date.UTC(tmp.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((tmp - yearStart) / 86400000 + 1) / 7);
  return `${tmp.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}

// ── In-memory fired guard (prevents double-send within same minute) ───────────
const _fired = new Set();

function firedKey(type, dateStr) {
  return `${type}::${dateStr}`;
}

function alreadyFired(type, dateStr) {
  return _fired.has(firedKey(type, dateStr));
}

function markFired(type, dateStr) {
  _fired.add(firedKey(type, dateStr));
  if (_fired.size > 200) {
    const first = _fired.values().next().value;
    _fired.delete(first);
  }
}

// ── Language picker ───────────────────────────────────────────────────────────
// Distribution: English 43%, Hinglish 35%, RomanHindi 20%, RomanTamil 3%
// Internal IDs avoid the word "Hindi"/"Tamil" so the AI doesn't default to native scripts.
const LANG_POOL = [
  ...Array(43).fill("English"),
  ...Array(35).fill("Hinglish"),
  ...Array(20).fill("RomanHindi"),
  ...Array(3).fill("RomanTamil"),
];

function pickLanguage() {
  return LANG_POOL[Math.floor(Math.random() * LANG_POOL.length)];
}

const LANG_INSTRUCTIONS = {
  English:
    "Write entirely in natural, warm English using only A-Z letters.",

  Hinglish:
    "Write exactly like an Indian medical student texting a friend — mixing spoken Hindi words with English, " +
    "ALL typed in Roman letters (A-Z only, never Devanagari). " +
    "Grammar guide:\n" +
    "  • Hindi verbs end naturally: karo, rakho, dekho, chalte raho, padh lo, try karo\n" +
    "  • English nouns fit seamlessly: case, practice, score, exam, concept, notes\n" +
    "  • Warm fillers: yaar, dost, bhai — used at end of sentence\n" +
    "  • Correct agreement: 'tera time aa raha hai', 'tu kar sakta hai', 'hum milke karenge'\n" +
    "  • Postpositions correct: ke liye, mein, par, se, tak, wala\n" +
    "  Excellent examples to match:\n" +
    "  title: 'Chal, ek case aur karo! 💪'   body: 'Sirf 10 minute chahiye, yaar. Tu kar sakta hai! 🩺'\n" +
    "  title: 'Subah ho gayi, dost! ☀️'       body: 'Chalo practice shuru karte hain — ek case aaj pakka! 📚'\n" +
    "  title: 'Raat mein bhi padhai? 🌙'       body: 'Teri mehnat rang layegi, bhai. Kal aur achi subah hogi! ✨'\n" +
    "  title: 'Ek aur try, yaar! 🚀'           body: 'Thoda aur — tera time bilkul aa raha hai! 🌟'\n" +
    "Produce similarly natural, grammatically correct Hinglish. A-Z only.",

  RomanHindi:
    "Write using only Hindi vocabulary, but spell every word phonetically in A-Z Roman letters " +
    "(as if you are typing Hindi in English script, like SMS transliteration). " +
    "Grammar guide:\n" +
    "  • Gender agreement: 'achha din' (m), 'achhi subah' (f), 'achha prayas' (m), 'nayi himmat' (f)\n" +
    "  • Verb forms: 'karo' (tum), 'karein' (aap-polite), 'kar' (tu-informal)\n" +
    "  • Postpositions: ke liye, mein, par, se, ka, ki, ke, ko\n" +
    "  • Natural flow — not choppy translations\n" +
    "  • Warm vocabulary: mehnat, hausla, sapna, safalta, prayas, himmat, umeed, tayyar\n" +
    "  Excellent examples to match:\n" +
    "  title: 'Subah Mubarak! 🌅'         body: 'Aaj ka din mehnat aur hausle se bhar do. Ek case zaroor karo! 💪'\n" +
    "  title: 'Aapka Waqt Aa Gaya! 🩺'   body: 'Sapna poora hone wala hai — bas ek aur prayas karo. Himmat rakho! 🌟'\n" +
    "  title: 'Shubh Ratri, Dost! 🌙'    body: 'Chain se soo — kal phir nayi umeed aur taazgi ke saath uthna. ✨'\n" +
    "  title: 'Chalte Raho! 💡'           body: 'Har ek case tumhe ek behtar doctor banata hai. Koshish jaari rakho! 🚀'\n" +
    "Produce similarly natural, grammatically correct Roman-script Hindi. A-Z only, NO Devanagari whatsoever.",

  RomanTamil:
    "Write using Tamil words and phrases, but spell every word in A-Z Roman letters (romanised Tamil, like how Tamil speakers type on phones). " +
    "Examples to match:\n" +
    "  title: 'Vanakkam! 🌅'              body: 'Nalla padinga — neenga mudiyum! Indru oru case try pannunga. 💪'\n" +
    "  title: 'Nalla Iravai! 🌙'          body: 'Nallapadikkai — kal nalla vizhippudan ezhunga! Ungal sapnam niraiverrum. ✨'\n" +
    "  title: 'Case Solve Pannunga! 🩺'  body: 'Konjam neram irukku — oru case paarunga. Neenga seiya mudiyum! 🌟'\n" +
    "A-Z only, NO Tamil script whatsoever.",
};

// ── Groq AI content generation ────────────────────────────────────────────────
const ROMAN_SYSTEM_MSG =
  "CRITICAL RULE: You must write ALL text exclusively in the Roman/Latin alphabet (A-Z). " +
  "This means NO Devanagari script (Hindi/Sanskrit), NO Tamil script, NO Arabic script, and NO other non-Latin scripts. " +
  "Even when the language is Hindi or Tamil, you MUST write every word phonetically using only English/Roman letters. " +
  "If you use any non-Latin character, your response is invalid. Only A-Z, numbers, spaces, punctuation, and emojis are allowed.";

// Detects Devanagari, Tamil, Arabic, Cyrillic, CJK, and other non-Latin scripts
// (does NOT flag emojis — emojis are fine)
function hasNonLatin(str) {
  return /[\u0250-\u02AF\u0370-\u03FF\u0400-\u04FF\u0500-\u05FF\u0600-\u06FF\u0900-\u097F\u0980-\u09FF\u0A00-\u0A7F\u0A80-\u0AFF\u0B00-\u0B7F\u0B80-\u0BFF\u0C00-\u0C7F\u0C80-\u0CFF\u0D00-\u0D7F\u0E00-\u0E7F\u4E00-\u9FFF\u3000-\u303F]/.test(str);
}

// Strip non-Latin script characters from a string (keep emojis, spaces, A-Z, punctuation)
function stripNonLatin(str) {
  return str
    .replace(/[\u0250-\u02AF\u0370-\u03FF\u0400-\u04FF\u0500-\u05FF\u0600-\u06FF\u0900-\u097F\u0980-\u09FF\u0A00-\u0A7F\u0A80-\u0AFF\u0B00-\u0B7F\u0B80-\u0BFF\u0C00-\u0C7F\u0C80-\u0CFF\u0D00-\u0D7F\u0E00-\u0E7F\u4E00-\u9FFF\u3000-\u303F]/g, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

async function groqJSONRaw(messages) {
  const res = await taskAI.chat.completions.create({
    model: TASK_AI_MODEL,
    messages,
    temperature: 0.9,
    max_tokens: 200,
    response_format: { type: "json_object" },
  });
  const text = res.choices[0]?.message?.content || "{}";
  try { return JSON.parse(text); } catch { return {}; }
}

async function groqJSON(prompt) {
  const messages = [
    { role: "system", content: ROMAN_SYSTEM_MSG },
    { role: "user",   content: prompt },
  ];
  let result = await groqJSONRaw(messages);

  // ── Pass 1: retry in pure English if non-Latin detected ──────────────────
  const combined = `${result.title || ""} ${result.body || ""}`;
  if (hasNonLatin(combined)) {
    console.warn("[notify] non-Latin script detected — retrying in English");
    result = await groqJSONRaw([
      { role: "system", content: ROMAN_SYSTEM_MSG },
      {
        role: "user",
        content:
          "You must write ONLY using A-Z letters (Roman/English alphabet).\n" +
          "Absolutely NO Devanagari, Tamil, Arabic, or any other script.\n" +
          "Language: English only.\n\n" + prompt,
      },
    ]);
  }

  // ── Pass 2: strip any remaining non-Latin chars as final safety ──────────
  const title = stripNonLatin(result.title || "");
  const body  = stripNonLatin(result.body  || "");

  return { title, body };
}

export async function generateMorningMessage() {
  const d = nowIST();
  const days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const day = days[d.getUTCDay()];
  const lang = pickLanguage();
  return groqJSON(
    `You write warm, short push notifications for CrLearn — a clinical reasoning training app for final-year Indian medical students (NEET-PG aspirants).

Generate a good morning message for ${day}. It should feel personal, encouraging, and medically themed.

Language rule: ${LANG_INSTRUCTIONS[lang]}

Emoji rule: Include 1–2 fitting emojis in the title AND 1–2 fitting emojis somewhere in the body. They should feel natural, not forced.

Rules: title ≤ 45 chars (including emojis), body ≤ 100 chars (including emojis).
Return JSON: {"title":"...","body":"..."}`
  );
}

export async function generateNightMessage() {
  const lang = pickLanguage();
  return groqJSON(
    `You write warm, short push notifications for CrLearn — a clinical reasoning training app for final-year Indian medical students.

Generate a good night / well-wish message. It should feel caring, calm, and gently motivational.

Language rule: ${LANG_INSTRUCTIONS[lang]}

Emoji rule: Include 1–2 fitting emojis in the title AND 1–2 fitting emojis somewhere in the body. They should feel natural, not forced.

Rules: title ≤ 45 chars (including emojis), body ≤ 100 chars (including emojis).
Return JSON: {"title":"...","body":"..."}`
  );
}

export async function generateFestivalMessage(festivalName) {
  const lang = pickLanguage();
  return groqJSON(
    `You write push notifications for CrLearn, a medical education app for Indian students.

Write a warm festival greeting push notification for: ${festivalName}
Connect it lightly to their medical journey.

Language rule: ${LANG_INSTRUCTIONS[lang]}

Emoji rule: Include 1–2 festival-appropriate emojis in the title AND 1–2 in the body.

Rules: title ≤ 45 chars (including emojis), body ≤ 100 chars (including emojis).
Return JSON: {"title":"...","body":"..."}`
  );
}

export async function checkTodayFestival() {
  const d = nowIST();
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  const humanDate = `${d.getUTCDate()} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
  const days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const dayName = days[d.getUTCDay()];

  const res = await groqJSON(
    `Today is ${humanDate} (${dayName}). You know all Indian festivals, cultural days, religious observances, and special days (Holi, Diwali, Eid, Durga Puja, Navratri, Rose Day, Valentine's Day, Friendship Day, Doctors' Day, etc.).

Is today a notable Indian festival, cultural event, or special day? Consider regional, national, and internationally celebrated days observed in India.
If YES: return JSON {"festival":"<name>","celebrate":true}
If NO:  return JSON {"festival":null,"celebrate":false}
Only return a festival if you are highly confident it falls today (${humanDate}).`
  );

  return res?.celebrate ? (res.festival || null) : null;
}

export async function generateNudgeMessage() {
  const lang = pickLanguage();
  return groqJSON(
    `You write push notifications for CrLearn, a clinical reasoning training app for final-year Indian medical students.

Generate a short, motivating push notification to encourage the student to practice a clinical case right now.
Make it feel urgent but warm.

Language rule: ${LANG_INSTRUCTIONS[lang]}

Emoji rule: Include 1–2 fitting emojis in the title AND 1–2 fitting emojis somewhere in the body. They should feel natural and energetic.

Rules: title ≤ 45 chars (including emojis), body ≤ 100 chars (including emojis).
Return JSON: {"title":"...","body":"..."}`
  );
}

// ── Weekly nudge schedule ─────────────────────────────────────────────────────
function buildValidDayCombos() {
  const combos = [];
  for (let a = 0; a <= 4; a++)
    for (let b = a + 1; b <= 5; b++) if (b - a <= 2)
      for (let c = b + 1; c <= 6; c++) if (c - b <= 2)
        for (let d = c + 1; d <= 6; d++) if (d - c <= 2)
          combos.push([a, b, c, d]);
  return combos;
}

const VALID_COMBOS = buildValidDayCombos();

export function generateWeekSchedule(istNow) {
  const now = istNow || nowIST();

  const dayOffsets = VALID_COMBOS[Math.floor(Math.random() * VALID_COMBOS.length)];

  const baseTimes = [10, 13, 16, 20];
  const dupIdx  = Math.floor(Math.random() * 4);
  let dropIdx;
  do { dropIdx = Math.floor(Math.random() * 4); } while (dropIdx === dupIdx);
  const times = [...baseTimes.filter((_, i) => i !== dropIdx), baseTimes[dupIdx]];
  for (let i = times.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [times[i], times[j]] = [times[j], times[i]];
  }

  const dow = now.getUTCDay();
  const daysToMon = dow === 0 ? -6 : 1 - dow;
  const monday = new Date(now.getTime() + daysToMon * 86400000);

  return dayOffsets.map((offset, i) => {
    const d = new Date(monday.getTime() + offset * 86400000);
    return { date: istDateStr(d), hour: times[i] };
  });
}

async function loadSchedule() {
  const { rows } = await query(
    `SELECT value FROM app_config WHERE key = 'nudge_schedule'`
  );
  if (!rows[0]) return null;
  try { return JSON.parse(rows[0].value); } catch { return null; }
}

async function saveSchedule(schedule) {
  await query(
    `INSERT INTO app_config (key, value) VALUES ('nudge_schedule', $1)
     ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
    [JSON.stringify(schedule)]
  );
}

export async function ensureWeekSchedule() {
  const existing = await loadSchedule();
  const week = isoWeekKey(nowIST());

  if (existing?.week === week && Array.isArray(existing?.slots) && existing.slots.length === 4) {
    return existing.slots;
  }

  const slots = generateWeekSchedule();
  await saveSchedule({ week, slots });
  console.log("[notify] new weekly nudge schedule:", JSON.stringify(slots));
  return slots;
}

export async function getScheduleInfo() {
  const slots = await ensureWeekSchedule();
  return { week: isoWeekKey(nowIST()), slots };
}

// ── Scheduler on/off toggle (persisted in app_config) ────────────────────────
export async function getSchedulerEnabled() {
  const { rows } = await query(
    `SELECT value FROM app_config WHERE key = 'notify_scheduler_enabled'`
  );
  return rows[0]?.value !== "false";
}

export async function setSchedulerEnabled(enabled) {
  await query(
    `INSERT INTO app_config (key, value) VALUES ('notify_scheduler_enabled', $1)
     ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
    [String(Boolean(enabled))]
  );
  console.log(`[notify] scheduler ${enabled ? "enabled" : "disabled"} by admin`);
  return Boolean(enabled);
}

// ── Notification runners ──────────────────────────────────────────────────────
export async function runMorningNotification({ force = false } = {}) {
  const dateStr = istDateStr(nowIST());
  if (!force && alreadyFired("morning", dateStr)) return { skipped: "already_sent" };
  markFired("morning", dateStr);

  try {
    const msg = await generateMorningMessage();
    const title = msg.title || "Good Morning ☀️";
    const body  = msg.body  || "Start your day strong — one case a day keeps failure away.";
    const result = await sendPushBroadcast({ title, body, link: "/dashboard", kind: "morning", tag: "daily-morning" });
    console.log(`[notify] morning sent — ${result.sent}/${result.total}`);
    return { ok: true, title, body, ...result };
  } catch (e) {
    console.warn("[notify] morning failed:", e.message);
    return { ok: false, error: e.message };
  }
}

export async function runNightNotification({ force = false } = {}) {
  const dateStr = istDateStr(nowIST());
  if (!force && alreadyFired("night", dateStr)) return { skipped: "already_sent" };
  markFired("night", dateStr);

  try {
    const msg = await generateNightMessage();
    const title = msg.title || "Good Night 🌙";
    const body  = msg.body  || "Rest well. Your brain consolidates learning as you sleep.";
    const result = await sendPushBroadcast({ title, body, link: "/dashboard", kind: "night", tag: "daily-night" });
    console.log(`[notify] night sent — ${result.sent}/${result.total}`);
    return { ok: true, title, body, ...result };
  } catch (e) {
    console.warn("[notify] night failed:", e.message);
    return { ok: false, error: e.message };
  }
}

export async function runFestivalCheck({ force = false } = {}) {
  const dateStr = istDateStr(nowIST());
  if (!force && alreadyFired("festival", dateStr)) return { skipped: "already_checked" };
  markFired("festival", dateStr);

  try {
    const festival = await checkTodayFestival();
    if (!festival) {
      console.log("[notify] festival check — no festival today");
      return { ok: true, festival: null };
    }
    console.log(`[notify] festival detected: ${festival}`);
    const msg = await generateFestivalMessage(festival);
    const title = msg.title || `Happy ${festival}! 🎉`;
    const body  = msg.body  || `Wishing you and your family a wonderful ${festival}.`;
    const result = await sendPushBroadcast({ title, body, link: "/dashboard", kind: "festival", tag: "festival-greeting" });
    console.log(`[notify] festival push sent — ${result.sent}/${result.total}`);
    return { ok: true, festival, title, body, ...result };
  } catch (e) {
    console.warn("[notify] festival check failed:", e.message);
    return { ok: false, error: e.message };
  }
}

export async function runFestivalForced(festivalName) {
  try {
    const msg = await generateFestivalMessage(festivalName);
    const title = msg.title || `Happy ${festivalName}! 🎉`;
    const body  = msg.body  || `Wishing you and your family a wonderful ${festivalName}.`;
    const result = await sendPushBroadcast({ title, body, link: "/dashboard", kind: "festival", tag: "festival-greeting" });
    return { ok: true, festival: festivalName, title, body, ...result };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

export async function runNudgeNotification({ force = false } = {}) {
  try {
    const msg = await generateNudgeMessage();
    const title = msg.title || "Time to Practice 🩺";
    const body  = msg.body  || "A quick case is waiting. Keep your streak alive!";
    const result = await sendPushBroadcast({ title, body, link: "/practice", kind: "nudge", tag: "weekly-nudge" });
    console.log(`[notify] nudge sent — ${result.sent}/${result.total}`);
    return { ok: true, title, body, ...result };
  } catch (e) {
    console.warn("[notify] nudge failed:", e.message);
    return { ok: false, error: e.message };
  }
}

// ── Main scheduler loop ───────────────────────────────────────────────────────
let _started = false;

export function startNotificationScheduler() {
  if (_started) return;
  _started = true;

  async function tick() {
    try {
      const ist  = nowIST();
      const hour = ist.getUTCHours();
      const min  = ist.getUTCMinutes();
      const dateStr = istDateStr(ist);

      // ── Skip everything if scheduler is disabled ─────────────────────────
      const enabled = await getSchedulerEnabled();
      if (!enabled) return;

      // ── 8:00 AM IST → Good Morning ──────────────────────────────────────
      if (hour === 8 && min < 5) {
        await runMorningNotification();
      }

      // ── 8:05 AM IST → Festival check ────────────────────────────────────
      if (hour === 8 && min >= 5 && min < 10) {
        await runFestivalCheck();
      }

      // ── Weekly nudge slots ───────────────────────────────────────────────
      if ([10, 13, 16, 20].includes(hour) && min < 5) {
        const nudgeKey = `nudge::${dateStr}::${hour}`;
        if (!_fired.has(nudgeKey)) {
          const slots = await ensureWeekSchedule();
          const match = slots.find((s) => s.date === dateStr && s.hour === hour);
          if (match) {
            _fired.add(nudgeKey);
            await runNudgeNotification();
          }
        }
      }

      // ── 11:00 PM IST → Good Night ───────────────────────────────────────
      if (hour === 23 && min < 5) {
        await runNightNotification();
      }

      // ── Sunday 11:50 PM IST → Pre-generate next week's schedule ─────────
      if (ist.getUTCDay() === 0 && hour === 23 && min >= 50) {
        const nextKey = `schedule-gen::${dateStr}`;
        if (!_fired.has(nextKey)) {
          _fired.add(nextKey);
          const nextMonday = new Date(ist.getTime() + 1 * 86400000);
          const slots = generateWeekSchedule(nextMonday);
          const week  = isoWeekKey(nextMonday);
          await saveSchedule({ week, slots });
          console.log("[notify] pre-generated next week schedule:", JSON.stringify(slots));
        }
      }

    } catch (e) {
      console.warn("[notify] scheduler tick error:", e.message);
    }
  }

  setTimeout(tick, 20_000);
  setInterval(tick, 5 * 60 * 1000);
  console.log("[notify] notification scheduler started (IST timezone)");
}
